export const ADD_DRIVER="add_driver"
export const GET_DRIVER='get_driver'
export const ALL_DRIVER="all_driver"
export const UPDATE_DRIVER="update_driver"
export const DELETE_DRIVER="delete_driver"
export const ERROR_DRIVER='error_driver'
export const CURRENT_DRIVER="current_driver"
export const CLEAR_CURRENT_DRIVER="clear_current_driver"
export const DRIVERS_KEY = "drivers"

export const ADD_TRACTOR="add_tractor"
export const GET_TRACTOR='get_tractor'
export const ALL_TRACTOR="all_tractor"
export const UPDATE_TRACTOR="update_tractor"
export const DELETE_TRACTOR="delete_tractor"
export const ERROR_TRACTOR='error_tractor'
export const CURRENT_TRACTOR="current_tractor"
export const CLEAR_CURRENT_TRACTOR="clear_current_tractor"
export const TRACTOR_KEY = "tractors"
