export const ADD_DRIVER="add_driver"
export const GET_DRIVER='get_driver'
export const ALL_DRIVER="all_driver"
export const UPDATE_DRIVER="update_driver"
export const DELETE_DRIVER="delete_driver"
export const ERROR_DRIVER='error_driver'
export const CURRENT_DRIVER="current_driver"
export const CLEAR_CURRENT_DRIVER="clear_current_driver"
export const DRIVERS_KEY = "drivers"